@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}

# @name create-account
POST {{baseUrl}}/account
Content-Type: application/json

{
  "name": "Fulano",
  "email": "fulano7@email.com",
  "password": "senhasecreta123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "fulano7@email.com",
  "password": "senhasecreta123"
}

###

# @name transaction
POST {{baseUrl}}/transaction/transfer
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "receiverId": "0539ddb8-0c04-4004-b739-df090daade23",
  "amount": "100.00"
}

###

# @name deposit
POST {{baseUrl}}/deposit
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "origin": "teste",
  "amount": "100.00"
}