@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.acessToken}}

# @name create-account
POST {{baseUrl}}/account
Content-Type: application/json

{
  "name": "Fulano",
  "email": "fulano3@email.com",
  "password": "senhasecreta123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "fulano3@email.com",
  "password": "senhasecreta123"
}

###

# @name transaction
POST {{baseUrl}}/transaction/transfer
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "receiverId": "9abc7e33-5956-4980-a4ea-d1f5e6f3db21",
  "amount": 100.00
}