version: '3.8'

services:
  postgres:
    container_name: carteira-financeira-pg
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: carteira-financeira
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres